clc;clear;close all;
[mapData, energies]= XraySpecFunctions.loadAllMapData("D4 map data");
mapData = XraySpecFunctions.noramalizeMaps(mapData);


figure
pcolor(mapData(:,:,1))
colorbar
figure
pcolor(mapData(:,:,2))
colorbar
figure
pcolor(mapData(:,:,3))
colorbar
figure
pcolor(mapData(:,:,4))
colorbar
figure
pcolor(mapData(:,:,5))
colorbar
figure
pcolor(mapData(:,:,6))
colorbar
figure
pcolor(mapData(:,:,7))
colorbar
figure
pcolor(mapData(:,:,8))
colorbar
figure
pcolor(mapData(:,:,9))
colorbar
figure
pcolor(mapData(:,:,10))
colorbar
figure
pcolor(mapData(:,:,11))
colorbar
figure
pcolor(mapData(:,:,12))
colorbar
figure
pcolor(mapData(:,:,13))
colorbar
figure
pcolor(mapData(:,:,14))
colorbar
figure
pcolor(mapData(:,:,15))
colorbar
figure
pcolor(mapData(:,:,16))
colorbar
figure
pcolor(mapData(:,:,17))
colorbar
figure
pcolor(mapData(:,:,18))
colorbar